/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DTokenIdRouteImport } from './routes/d.$tokenId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenIdRoute = DTokenIdRouteImport.update({
  id: '/d/$tokenId',
  path: '/d/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/d/$tokenId': typeof DTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/d/$tokenId': typeof DTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/d/$tokenId': typeof DTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/d/$tokenId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/d/$tokenId'
  id: '__root__' | '/' | '/d/$tokenId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DTokenIdRoute: typeof DTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$tokenId': {
      id: '/d/$tokenId'
      path: '/d/$tokenId'
      fullPath: '/d/$tokenId'
      preLoaderRoute: typeof DTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DTokenIdRoute: DTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
